### ISSUE TITLE
MPG X670e CARBON WIFI (MT7922) can't not passthrough 

### ISSUE THREAD

**Issue by ChomperT** [pgj/freebsd-wifibox#106] opened 2024-08-16 14:18 UTC
### Description

Hello, when using WiFiBox on an MSI motherboard, do I need to make any additional configurations to use it? It worked successfully once the day before yesterday, but since then, I have been encountering the following issue:

`ppt0 mem 0xf930300000-0xf9303fffff,0xf6600000-0xf6607fff at device 0.0 on pci13`
`tap0: link state changed to UP`
`wifibox0: link state changed to UP`
`pci0:13:0:0: Transactions pending after FLR!`

### Host operating system

```shell
Output of `uname -a`.
FreeBSD N 15.0-CURRENT FreeBSD 15.0-CURRENT #0 main-n271670-bd4f2023bb05: Thu Aug 15 03:22:49 UTC 2024     root@releng3.nyi.freebsd.org:/usr/obj/usr/src/amd64.amd64/sys/GENERIC amd64
```

### Wireless NIC

```shell
Relevant output of `pciconf -lv`.
none3@pci0:13:0:0:      class=0x028000 rev=0x00 hdr=0x00 vendor=0x14c3 device=0x0616 subvendor=0x14c3 subdevice=0x0616
    vendor     = 'MEDIATEK Corp.'
    device     = 'MT7922 802.11ax PCI Express Wireless Network Adapter'
    class      = network
```

### Wifibox version

```shell
Output of `wifibox version`.  Note that only the latest version is supported.
wifibox version 0.13.0
Disk image checksum: 29e3e7a0bc4cc0468e64b19d5aff26795d022204436653cd697a7f11d3dfdb85
```

### Disk image type and version

The kind of VM image in use, e.g. Wifibox/Alpine, and its version.
wifibox-alpine-mediatek-20240506 Wifibox guest based on Alpine Linux
wifibox-core-0.13.0            Wifibox core functionality
wifibox-mediatek-1.4.2         Wireless card driver via virtualized Linux

### Changes to the default configuration files

```shell
Include relevant sections from all the configuration files that contain local changes and may help to reproduce the problem.
```

### Logs

```shell
Please copy and paste any relevant log output from the following sources:

- /var/log/wifibox.log (with DEBUG logging verbosity)
- /var/run/wifibox/appliance/log/dmesg
- /var/run/wifibox/appliance/log/messages

Hint: The DEBUG log verbosity could be configured in the `core.conf` file, which is located in the `$LOCALBASE/etc/wifibox` directory.
```

### Additional context

Add any other context about the problem here that might help the investigation.

### Have you tried to turn it on and off?

- [X] Yes, I have read all the manual pages first!

**Comment by pgj** [comment] 2024-08-18 07:13
Thanks for the report.   I think this is a duplicate of https://github.com/pgj/freebsd-wifibox/issues/73#issuecomment-2067526865 of which had [a follow-up on the `freebsd-virtualization` mailing list](https://lists.freebsd.org/archives/freebsd-virtualization/2024-April/002090.html) but without any current results so far.

**Comment by pgj** [comment] 2024-08-28 07:12
I am closing this ticket for now as a duplicate.

**Closed by pgj** 2024-08-28 07:12 UTC
Labels: bug, duplicate, base system
