### ISSUE TITLE
mbedtls-2.28.7-r0.apk doesn't seem to exist in /usr/ports/distfiles/wifibox-alpine

### ISSUE THREAD

**Issue by mkohanim** [pgj/freebsd-wifibox#101] opened 2024-05-13 18:30 UTC
### Description

A clear and concise description of what the problem is.  What is expected from the application?
Trying to build wifibox-alpine (v20240506) on 13.2p11.  It seems that it cannot find mbedtls.

### Host operating system

```shell
Output of `uname -a`.
FreeBSD bsdev.isy.io 13.2-RELEASE-p11 FreeBSD 13.2-RELEASE-p11 GENERIC amd64
```

### Wireless NIC

```shell
Relevant output of `pciconf -lv`.
This is a build environment with no wireless nics.
```

### Wifibox version

```shell
Output of `wifibox version`.  Note that only the latest version is supported.
This is a build environment.
```

### Disk image type and version

The kind of VM image in use, e.g. Wifibox/Alpine, and its version.
This is a build environment.

### Changes to the default configuration files

```shell
Include relevant sections from all the configuration files that contain local changes and may help to reproduce the problem.

XX_MDNS
XX_FORWARDING
```

### Logs

```shell
Please copy and paste any relevant log output from the following sources:

Build issue.
```

### Additional context

Add any other context about the problem here that might help the investigation.

### Have you tried to turn it on and off?

- [X] Yes, I have read all the manual pages first!

**Comment by pgj** [comment] 2024-05-13 22:28
The `snapshots` directory on the https://mirror.fel.cvut.cz Alpine Linux mirror became unavailable that Wifibox uses to retrieve the APK packages from upstream.  The APKs that are required for building the port with the default options are cached by the FreeBSD distcache.  `mbedtls` is only used optionally, and distcache did not mirror that, that is why it is now unavailable.

I do not know if that is transient error -- I will have to look into this more deeply to see how to address the root cause.  Thanks for reporting!

**Comment by mkohanim** [comment] 2024-05-14 19:40
Hi Gábor, if wifibox-alpine does not use mbded-tls, would you mind removing it? I have not been able to make a build for our 13.2 release. Thank you.

With kind regards,

******************************
  Michel Kohanim
             CEO

  (p) 818.631.0333
  http://www.universal-devices.com<http://www.universal-devices.com/>
******************************

**Comment by pgj** [comment] 2024-05-14 22:18
`wifibox-alpine` uses `mbed-tls`, it is a dependency of `mDNSResponder`.  But `mDNSResponder` is not part of the default package, that is why the respective distfiles did not get cached.  You can still build `wifibox-alpine` but without `mDNSResponder`.

**Comment by mkohanim** [comment] 2024-05-14 22:20
But I do use nDNSResponder.

With kind regards,

******************************
  Michel Kohanim
             CEO

  (p) 818.631.0333
  http://www.universal-devices.com<http://www.universal-devices.com/>
******************************

**Comment by pgj** [comment] 2024-05-14 22:36
The complete solution requires some more work, hopefully I can get to fixing it this week.  As a temporary workaround, I published the missing [`mbedtls-2.28.7-r0.apk`](https://github.com/pgj/freebsd-wifibox-alpine/releases/download/packages/mbedtls-2.28.7-r0.apk) file.  Download and copy it over to the `wifibox-alpine` subdirectory of `DISTDIR` of the ports tree in use.  That is usually `/usr/ports/distfiles` but I may be different on your configuration.

**Comment by pgj** [comment] 2024-05-15 07:11
Please test the build with this version of the port:

https://github.com/pgj/freebsd-wifibox-port/tree/bd648530ce2983be98a97e8c8ea24ab6b9c1ea9a

**Comment by mkohanim** [comment] 2024-05-15 23:45
Gábor, thank you very much! It worked!!! On one of the tests, we got 490Mbps download speed!!!! Bravo!

With kind regards,

******************************
  Michel Kohanim
             CEO

  (p) 818.631.0333
  http://www.universal-devices.com<http://www.universal-devices.com/>
******************************

**Comment by pgj** [comment] 2024-05-17 08:24
I am glad to hear to that!  I am now closing the issue.

**Closed by pgj** 2024-05-17 08:24 UTC
Labels: bug, wifibox-alpine
