### ISSUE TITLE
use dns servers from udhcpc

### ISSUE THREAD

**Issue by sheridans** [pgj/freebsd-wifibox#30] opened 2022-07-25 21:36 UTC
Have this working fine specifying public dns servers via udhcpd.conf via options, however it would be useful to be able to update the dns servers in resolv.conf on the host with those from udhcpc on the bhyve client, as it break local dns resolution (especially with local histnames, vlans, etc).

For example when udhcpc runs, it creates a (local) file in bhyve located at /tmp/resolv.conf. There doesn't seem anyway to get this to the host. If there was a way of linking /etc/resolv.conf on the host to say (writable) /media/etc/resolv.conf on the vm as you can link the wpa_supplicant.conf that may help?

Sorry if I have missed something and there is a way to do this.

**Comment by pgj** [comment] 2022-07-25 23:37
Hi @sheridans: I am not sure if I see you meant here.  The `/etc/resolv.conf` file would always be re-generated by `resolvconf(8)` when `dhclient(8)` gets an IP address via `wifibox0` on the host.  The `resolv.conf` file that is generated by `udhcpc` could be exported to the host through `/media/etc` for sure, but what would you do with that file?  Note that `wpa_supplicant.conf(5)` is a separate file that lives under `$LOCALBASE/etc/wifibox/wpa_supplicant` and it is not that same as `/etc/wpa_supplicant.conf` -- they only share the same format.

**Comment by sheridans** [comment] 2022-07-26 01:42
I'm guessing I set it up wrong, i actually created a link to the `/etc/wpa_supplicant.conf` as opposed to copying it:

```
$ cd /usr/local/etc/wifibox/wpa_supplicant
$ doas mv wpa_supplicant.conf wpa_supplicant.bak
$ doas ln /etc/wpa_supplicant.conf ./
```

I was somehow looking at doing something similar with `resolv.conf` .

**Comment by pgj** [comment] 2022-07-26 23:02
Did I understand it well that you have a DHCP server on the wireless network that forwards some special configuration for the clients?  And the problem is that this set of information is lost somewhere between `udhcpc` and `udhcpd`?

Ideally, the FreeBSD host (the client of the client) should get all the extra data from the DHCP server in the guest, which is then relayed to `/etc/resolv.conf`.  I think a potential solution for the problem could be to implement a [1:1 NAT or networking bridging](https://github.com/pgj/freebsd-wifibox/issues/18), perhaps.  Otherwise I can imagine only various workarounds as you also suggested.  Let me think about this.

**Comment by sheridans** [comment] 2022-07-28 14:33
In my case it's not dhcp options causing an issue, simply name resolution. For example at work we have hostnames which only resolve internally so using public dns servers causes a problem. Having to manually edit `/etc/resolv.conf` to manually point to local dns resolvers is a bit of a pain. 

It wouldn't be an issue with a static desktop that never moves as you could just set the `opt dns 192.168.1.1` in udhcpd for example as it would never change. With a laptop that's carried between various places with local dns servers requires constantly editing `/etc/resolv.conf` hence if there was a way to export the '/tmp/resolv.conf' from the alpine guest to the main host would at least be able to script copy that over the hosts `/etc/resolv.conf`

hopefully this makes sense

**Comment by pgj** [comment] 2022-07-28 19:30
Okay, I will see what I can do to support this use case.

**Comment by pgj** [comment] 2022-09-17 09:58
@sheridans I have added support for propagating the DNS information between `udhcpc` and `udhcpd`.  You can test it by installing the `net/wifibox-alpine` port from the development tree: https://github.com/pgj/freebsd-wifibox-port/tree/1302885fa7ae2c8e078766b305004beacd245f61 .  Let me know how it works for you.

**Comment by pgj** [comment] 2022-10-14 17:58
I did not receive any answer on this, so I assume my proposal is acceptable.  Therefore I am closing this ticket.  Please re-open if there is anything to follow up.

**Closed by pgj** 2022-10-14 17:58 UTC
Labels: bug

**Comment by sheridans** [comment] 2022-10-14 18:10
Hadn't got around to trying it, thanks for the follow up, will let you know how it goes.

**Comment by sheridans** [comment] 2023-07-19 15:17
Sorry for late reply, works perfectly after testing on multiple systems - thank you!

**Comment by pgj** [comment] 2023-07-19 22:55
That is great to hear, you are welcome.  Thanks for the feedback.
