### ISSUE TITLE
Two 'wifibox start' processes

### ISSUE THREAD

**Issue by mkohanim** [pgj/freebsd-wifibox#36] opened 2022-08-24 14:09 UTC
Hi Gábor,

Is there any reason why there are 2 x 'wifibox start' processes?

With kind regards,
Michel

**Comment by pgj** [comment] 2022-08-24 22:32
That is because the `wifibox` script launches programs, e.g. `bhyve` while reading and saving their outputs.  That is why it has to fork: one instance waits for the program in question to terminate and the other instance processes the generated output line by line (even if logging is disabled).  Hence it is an expected behavior.

**Comment by mkohanim** [comment] 2022-08-25 14:03
Thank you for the explanation.

**Comment by pgj** [comment] 2022-08-27 16:09
I consider this issue answered and I am closing ticket now.

**Closed by pgj** 2022-08-27 16:09 UTC
